name: Training Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'pipelines/**'
      - '.github/workflows/training.yml'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn pandas numpy keras jax[cpu] boto3 packaging mlflow setuptools python-dotenv psutil metaflow matplotlib

    - name: Create MLflow directories and start server
      run: |
        mkdir -p mlruns
        mlflow server \
          --host 127.0.0.1 \
          --port 5000 \
          --backend-store-uri sqlite:///mlflow.db \
          --default-artifact-root ./mlruns \
          --workers 4 &
        sleep 10  # Give MLflow server time to start
        
    - name: Run Training Pipeline
      env:
        MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING: true
        MLFLOW_HTTP_REQUEST_MAX_RETRIES: 5
        MLFLOW_HTTP_REQUEST_TIMEOUT: 300
        MLFLOW_TRACKING_INSECURE_TLS: true
      run: |
        python pipelines/training.py --environment=pypi run

    - name: Upload MLflow artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: |
          mlruns/
          mlflow.db
        retention-days: 7

    - name: Upload Model if accuracy threshold met
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model/
        retention-days: 7 