name: Training Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'pipelines/**'
      - '.github/workflows/training.yml'

jobs:
  train:
    runs-on: ubuntu-latest
    
    services:
      mlflow:
        image: ghcr.io/mlflow/mlflow:latest
        ports:
          - 5000:5000
        options: >-
          --health-cmd "curl -f http://localhost:5000/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn pandas numpy keras jax[cpu] boto3 packaging mlflow setuptools python-dotenv psutil metaflow matplotlib

    - name: Create MLflow directories
      run: |
        mkdir -p mlruns
        
    - name: Run Training Pipeline
      env:
        MLFLOW_TRACKING_URI: http://localhost:5000
        MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING: true
        MLFLOW_HTTP_REQUEST_MAX_RETRIES: 5
        MLFLOW_HTTP_REQUEST_TIMEOUT: 300
        MLFLOW_TRACKING_INSECURE_TLS: true
      run: |
        python pipelines/training.py --environment=pypi run

    - name: Upload MLflow artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: |
          mlruns/
          mlflow.db
        retention-days: 7

    - name: Upload Model if accuracy threshold met
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model/
        retention-days: 7 